const menuToggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('.main-nav');
const navLinks=document.querySelectorAll('.main-nav a');
menuToggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open)});
navLinks.forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false')}));
const backTop=document.querySelector('.back-top');
window.addEventListener('scroll',()=>backTop.classList.toggle('show',window.scrollY>500),{passive:true});
backTop.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
const sections=[...document.querySelectorAll('main section[id]')];
const links=[...document.querySelectorAll('.main-nav>a[href^="#"]')];
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+entry.target.id))}}),{rootMargin:'-35% 0px -55% 0px',threshold:0});
sections.forEach(s=>observer.observe(s));
document.getElementById('year').textContent=new Date().getFullYear();
const form=document.getElementById('quote-form');
form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const subject=encodeURIComponent('New Rebar Quote Request - '+data.get('name'));const body=encodeURIComponent(`Name: ${data.get('name')}\nCompany: ${data.get('company')}\nEmail: ${data.get('email')}\nPhone: ${data.get('phone')}\nService: ${data.get('service')}\n\nProject Details:\n${data.get('details')}`);window.location.href=`mailto:bharathm3726@outlook.com?subject=${subject}&body=${body}`});
